config/routes.rb
Rails.application.routes.draw do
  get 'login/index'
  get 'submit/index'
  get 'comments/index'
  get 'welcome/index'
	get '/login', to: 'login#index'
	get '/news', to: 'articles#index'
	get '/item', to: 'articles#show'
	get '/newcomments', to: 'comments#index'
	get '/submit', to: 'articles#new'
	get '/about', to: 'welcome#about'
  root 'articles#index'
	
	delete '/logout',  to: 'sessions#destroy'
	
	resources :accounts do
		resources :articles
	end
	resources :articles do
		resources :comments
	end
	resources :sessions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	
	scope '/v0' do
		scope '/item' do
			scope '/create' do
				post '/' => 'articles#apicreate'
			end
			get '/:name' => 'articles#apishow'
		end
	end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
  end
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/login/index.html.erb
<% content_for :title, "Login" %>
<%= render 'welcome/header' %>
	<section>
		<!-- Login -->
		<p id="notice" class="center"><%= notice %></p>
		<div class="formStyle">
			<%= form_with scope: :session, url: sessions_path, local: true, class: 'center' do |form| %>
				<table width="200" border="0">
					<tr>
						<td align="center" colspan="2">
							<h2>Login</h2>
						</td>
					</tr>
					<tr>
						<td width="50%">
							<%= form.label :username %>:
						</td>
						<td>
							<%= form.text_field :username, class: 'txtFieldLoginStyle' %>
						</td>
					</tr>
					<tr>
						<td>
							<%= form.label :password %>:
						</td>
						<td>
							<%= form.password_field :password, class: 'txtFieldLoginStyle' %>
						</td>
					</tr>
					<tr>
						<td align="center" colspan="2">
							<%= form.submit 'login', class: 'addSubmittion' %>
						</td>
					</tr>
				</table>
			<% end %>
		</div>
		<!-- Login - close -->
		
		<!-- Create Account -->
		<div class="formStyle">
			<%= form_with scope: :account, url: accounts_path, local: true, class: 'center' do |form| %>
				<table width="200" border="0">
					<tr>
						<td align="center" colspan="2">
							<h2>Create Account</h2>
						</td>
					</tr>
					<tr>
						<td width="50%">
							<%= form.label :username %>:
						</td>
						<td>
							 <%= form.text_field :username, class: 'txtFieldLoginStyle' %>
						</td>
					</tr>
					<tr>
						<td>
							<%= form.label :password %>:
						</td>
						<td>
							<%= form.password_field :password, class: 'txtFieldLoginStyle' %>
						</td>
					</tr>
					<tr>
						<td align="center" colspan="2">
							<%= form.submit 'create', class: 'addSubmittion' %>
						</td>
					</tr>
				</table>
			<% end %>
		</div>
		<!-- Create Account - close -->
		
	</section>
<%= render 'welcome/footer' %>